### ISSUE TITLE
Async operation

### ISSUE THREAD

**Issue by dapetcu21** [HenrikJoreteg/templatizer#78]
It would be nice to be able to do all IO asynchronously. There are a lot of `readFileSync`s around right now.

**Comment by lukekarrys** [comment]
Hey @dapetcu21. Yeah I've debated before whether it makes sense to change all the `fs` methods from the sync to async versions, and I've come to the conclusion that I don't think it would be worth the effort for this module. It's a dev tool, so I'm generally ok with it being sync. There are also calls to `jade.compile` and `uglifyjs.minify` which are both sync and don't have async counterparts.

Do you have a specific use case where the sync calls are causing a problem?

**Comment by dapetcu21** [comment]
Yes. I'm planning to compile stuff server-side and it would be a ton more efficient to base my compile queues on async operations rather than spuriously spawn processes for each compile. `Jade.compile` and `uglify.minify` don't really count for this since they're mostly CPU-intensive tasks (well, at least if you don't use any `include`s in your jades). They would count for CPU time well spent.

**Comment by lukekarrys** [comment]
Thanks for the explanation @dapetcu21. That makes sense and if you're going to be compiling in queues, then I see how it make things much easier if it was all async. I've never had the need for it thus far, but it'd be nice if only because it'd make the API more node-like.

Unfortunately I won't have the time to try this out in a branch right now, but if you wanted to try a PR for it I would definitely accept it. It'd be a major version bump, but I don't think thats an issue.
