### ISSUE TITLE
Provide jadeRuntime as dependency

### ISSUE THREAD

**Issue by klausbayrhammer** [HenrikJoreteg/templatizer#89]
Hi,

We have a couple of different modules and we use templatizer to compile the jade templates. Since we don't want to serve the inlined jade-runtime multiple times (once per module) we tried to use `amdDependencies` to inject the jade-runtime.

The straightforward way would be something like this:

```javascript
templatizer(templatizerSrc, templatizerDest, {amdDependencies: ['jade-runtime'], inlineJadeRuntime:false})
```

The jadeRuntime is not inlined but unfortunatly `jade-runtime` is used as the dependency-name which results in the following code-block (which is syntactically incorrect)
```javascript
...
}(this, function (jade-runtime) {
...
```

Wouldn't it be more expressive to either:
* Expect the jade-runtime to be provided as dependency when the `inlineJadeRuntime` parameter is set to false
* provide an explicit parameter to specify the name of the jade-runtime dependency

**Comment by lukekarrys** [comment]
> Expect the jade-runtime to be provided as dependency when the inlineJadeRuntime parameter is set to false

I think that is currently the case. I've never actually used `templatizer` with the `amd` functionality, but I saw this in the docs, from under the `inlineJadeRuntime` section:  *Instead a `jade` module is expected as `amdDependency` parameter.*

> provide an explicit parameter to specify the name of the jade-runtime dependency

When the jade templates are compiled to javascript functions, they expect the runtime to be called `jade`. I'd rather not allow that to be renamed to a different variable since it would require parsing each compiled template and replacing `jade.RUNTIME_FN` with `customVariable.RUNTIME_FN`.

I'm curious if it works if you set `amdDependencies: ['jade']`?

Alternatively, I just learned today that `jade-runtime` is now a standalone module: https://github.com/jadejs/jade-runtime. This issue has come up before, and I agree it would be best if the runtime was not inlined. I think it would require a major version bump, but I think the right move would be to add `jade-runtime` as a peer dependency and always make the runtime a parameter passed in to the `templatizer` function and update the UMD template to use [the dependency format](https://github.com/umdjs/umd/blob/master/returnExports.js#L17)

What do you think about that?

**Comment by lukekarrys** [comment]
@klausbayrhammer So I started work on what I think is a long overdue v2 which simplifies the code by removing a number of options. See the full [changes here](https://github.com/HenrikJoreteg/templatizer/pull/91/files#diff-04c6e90faac2675aa89e2176d2eec7d8R205) but the biggest is probably no more AMD/global support.

So now the runtime will be included via a `require('jade-runtime')` call so there will be no more duplicate runtimes. And the compiled source will be available as a Common JS module only. I don't have very much knowledge about the AMD ecosystem (another reason for the changes), but I assume something like the [`require.js` conversion tool](http://requirejs.org/docs/commonjs.html#autoconversion) or [`amd-wrap`](https://www.npmjs.com/package/amd-wrap) would be able to be used to have the new format work within an AMD loader system. Is that true? Any insight you can provide about if these changes would work for you would be greatly appreciated.

**Comment by klausbayrhammer** [comment]
Thanks for the fix! Really appreciate it!
